### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by sriram155** [bemoss/bemoss_os#37]
Hi,
I'm having hard time installing BEMOSS. I've tried using my Mac as well as my Raspberry Pi. I end up at the same error while installing cassandra that cannot activate /bin/activate and the installer terminates. 

On my Mac, I've Ubuntu 14.04.4 LTS installed on my Parallels. Followed all the instructions as stated on the the Wiki. 

When I tried installing python-virtualenv and making the workspace folder as a virtualenv, the installation works well, however, after reboot, when I launch the GUI and click Run BEMOSS, it is prompting me to install again. I've tried the entire process almost 50 times so far with no success. Please help.

**Comment by zxymark221** [comment]
Hi, this issue recently occurs since the URL for downloading virtualenv has been changed.  Please see VOLTTRON [Issue 600](https://github.com/VOLTTRON/volttron/issues/600) for more detail.

We have push the update in BEMOSS master branch, please pull and try again.

Thanks,
BEMOSS Team
